name: Deploy sepolia testnet to subgraph studio graphnode
run-name: Deploy ${{ github.ref_name }} to subgraph studio graphnode by @${{ github.actor }}
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  subgraph:
    name: Subgraph - Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: graph auth ${{ secrets.GRAPH_AUTH_KEY }}
      - run: sh deploy.sh
        env:
          NETWORK_NAME: "sepolia"
          START_BLOCK: "0"
          SUBGRAPH_NAME: "gu-corp/eip721"
          GRAPH_NODE_URL: "https://api.studio.thegraph.com/deploy/"
          IPFS_URL: "https://api.thegraph.com/ipfs/"
          VERSION: "${{ github.ref_name }}"
